/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package clientewsvuelos;

import entities.Lineas;

/**
 *
 * @author Nestor
 */
public class Cliente extends javax.swing.JFrame {

    /**
     * Creates new form Cliente
     */
    public Cliente() {
        initComponents();
        getOrigin();
        getDestination();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scrollTexto = new javax.swing.JScrollPane();
        texto = new javax.swing.JTextArea();
        lineas = new javax.swing.JComboBox<>();
        destinoBox = new javax.swing.JComboBox<>();
        origenBox = new javax.swing.JComboBox<>();
        origen = new javax.swing.JLabel();
        destino = new javax.swing.JLabel();
        verLineas = new javax.swing.JButton();
        pasajeros = new javax.swing.JLabel();
        pasajerosField = new javax.swing.JTextField();
        correo = new javax.swing.JLabel();
        correoField = new javax.swing.JTextField();
        Aceptar3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de tickets");
        setResizable(false);

        texto.setEditable(false);
        texto.setColumns(20);
        texto.setRows(5);
        texto.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        scrollTexto.setViewportView(texto);

        lineas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        destinoBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                destinoBoxActionPerformed(evt);
            }
        });

        origenBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                origenBoxActionPerformed(evt);
            }
        });

        origen.setText("Origen:");

        destino.setText("Destino:");

        verLineas.setText("Ver líneas");
        verLineas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verLineasActionPerformed(evt);
            }
        });

        pasajeros.setText("Pasajeros:");

        pasajerosField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasajerosFieldActionPerformed(evt);
            }
        });

        correo.setText("Correo:");

        correoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correoFieldActionPerformed(evt);
            }
        });

        Aceptar3.setText("Aceptar");
        Aceptar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Aceptar3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lineas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(verLineas)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(pasajeros)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(pasajerosField, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(correo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origen)
                                    .addComponent(destino))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(origenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(destinoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(scrollTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(Aceptar3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(verLineas)
                        .addGap(29, 29, 29)
                        .addComponent(lineas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(origen)
                            .addComponent(origenBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(destinoBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(destino))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pasajeros)
                            .addComponent(pasajerosField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(correo)
                            .addComponent(correoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(scrollTexto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Aceptar3)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void verLineasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verLineasActionPerformed
        Lineas lineas=new Lineas();
        String[] lineasA=lineas.getAllLineas_XML().split(";");
        String textoS="";
        for (int i = 0; i < lineasA.length; i++) {
            textoS+=lineasA[i]+"\n";
        }
        texto.setText(textoS);
        
    }//GEN-LAST:event_verLineasActionPerformed

    private void getOrigin(){
        Lineas lineas=new Lineas();
        String[] origen=lineas.getAllOrigin_XML().split(":");
        origenBox.addItem("-");
        for (int i = 0; i < origen.length; i++) {
            origenBox.addItem(origen[i]);
        }
    }
    
    private void getDestination(){
        Lineas lineas=new Lineas();
        String[] destino=lineas.getAllDestination_XML().split(":");
        destinoBox.addItem("-");
        for (int i = 0; i < destino.length; i++) {
            destinoBox.addItem(destino[i]);
        }
    }
    private void pasajerosFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasajerosFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pasajerosFieldActionPerformed

    private void correoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_correoFieldActionPerformed

    private void Aceptar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Aceptar3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Aceptar3ActionPerformed

    private void origenBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_origenBoxActionPerformed
        
        String origen=(String)origenBox.getSelectedItem();
        String destino= (String) destinoBox.getSelectedItem();
        if(!origen.equals("-") && !destino.equals("-")){
            texto.setText(busqueda());
        }
    }//GEN-LAST:event_origenBoxActionPerformed

    private void destinoBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_destinoBoxActionPerformed

        String origen=(String)origenBox.getSelectedItem();
        String destino= (String) destinoBox.getSelectedItem();
        if(!origen.equals("-") && !destino.equals("-")){
            texto.setText(busqueda());
        }
    }//GEN-LAST:event_destinoBoxActionPerformed

    private String busqueda(){
        Lineas l=new Lineas();
        String result="";
        String[] lineasA=l.getLinea_XML((String)origenBox.getSelectedItem(), (String) destinoBox.getSelectedItem()).split(":");
        for (int i = 0; i < lineasA.length; i++) {
            result+=lineasA[i]+"\n";
        }
        return result;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Aceptar3;
    private javax.swing.JLabel correo;
    private javax.swing.JTextField correoField;
    private javax.swing.JLabel destino;
    private javax.swing.JComboBox<String> destinoBox;
    private javax.swing.JComboBox<String> lineas;
    private javax.swing.JLabel origen;
    private javax.swing.JComboBox<String> origenBox;
    private javax.swing.JLabel pasajeros;
    private javax.swing.JTextField pasajerosField;
    private javax.swing.JScrollPane scrollTexto;
    private javax.swing.JTextArea texto;
    private javax.swing.JButton verLineas;
    // End of variables declaration//GEN-END:variables
}
